# Generated by Django 5.1.7 on 2025-04-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='external_id',
            field=models.CharField(blank=True, help_text='External ID from the source API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='source',
            field=models.CharField(blank=True, help_text="Source of the plant data (e.g., 'permapeople')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
