# Generated by Django 5.1.7 on 2025-04-06 21:04

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_created_at_profile_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='source',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comment'),
        ),
        migrations.AddField(
            model_name='plant',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='plants', to='main.comment'),
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='plant_photo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_comments', to='main.plant'),
        ),
    ]
