# Generated by Django 5.1.7 on 2025-04-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_comment_author_rename_user_plant_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
